name: Super-Linter

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
     - uses: actions/checkout@v2
      
     - name: Install dependencies
        run: |
          pip install poetry
          make install

     - name: Run linter and pytest
       run: make lint
