name: Super-Linter

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]
    steps:
     - uses: actions/checkout@v2
      
     - name: Install dependencies
       run: pip install poetry

     - name: Install dep
       run: make install

     - name: Run linter and pytest
       run: make lint
